<a href="https://colab.research.google.com/github/himeshmehta/Handwritten-digit-Recognizer/blob/master/handwritten_digit_classifier_in_logistic_regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# load data from keras
from keras.datasets import mnist
(X_train , Y_train),(X_test,Y_test) = mnist.load_data()

Using TensorFlow backend.


In [0]:
def data_summary( X_train , Y_train , X_test  , Y_test ):
  print("the shape of X_train: ",X_train.shape)
  print("the shape of Y_train: ",Y_train.shape)
  print("the shape of X_test: ",X_test.shape)
  print("the shape of Y_test: ",Y_test.shape)
  return 

In [4]:
data_summary(
    X_train,
    Y_train,
    X_test,
    Y_test
)

the shape of X_train:  (60000, 28, 28)
the shape of Y_train:  (60000,)
the shape of X_test:  (10000, 28, 28)
the shape of Y_test:  (10000,)


In [5]:
# change the shape of X_train,X_test
X_train = X_train.reshape(X_train.shape[0],784)
X_test  = X_test.reshape(X_test.shape[0],784)
data_summary(
    X_train,
    Y_train,
    X_test,
    Y_test
)


the shape of X_train:  (60000, 784)
the shape of Y_train:  (60000,)
the shape of X_test:  (10000, 784)
the shape of Y_test:  (10000,)


In [0]:
# feature scaling
X_train = X_train/255
X_test  = X_test/255

In [7]:
# create a logistic regression model
from sklearn.linear_model import LogisticRegression
model  = LogisticRegression()
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test) 

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [8]:
# measure the accuracy 
from sklearn import metrics
print("accuracy of this model is ",metrics.accuracy_score(Y_test,Y_pred))

accuracy of this model is  0.9201


In [10]:
# print confusion metric
print("confusion mteric is ")
print(metrics.confusion_matrix(Y_test,Y_pred))

confusion mteric is 
[[ 960    0    1    2    0    5    6    3    1    2]
 [   0 1112    3    1    0    1    5    1   12    0]
 [   8    8  920   20    9    5   10   11   37    4]
 [   4    0   17  919    2   22    4   12   21    9]
 [   1    2    5    3  914    0   10    2    7   38]
 [  10    2    0   42   10  769   17    7   28    7]
 [   9    3    7    2    6   20  907    1    3    0]
 [   2    7   22    5    8    1    1  950    5   27]
 [  10   14    5   21   14   27    7   11  853   12]
 [   8    8    2   13   31   14    0   24   12  897]]
