<a href="https://colab.research.google.com/github/himeshmehta/Handwritten-digit-Recognizer/blob/master/handwritten_digit_classifier_using_SVC_and_hyperparamter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
# load data from keras
from keras.datasets import mnist
(X_train , Y_train),(X_test,Y_test) = mnist.load_data()

Using TensorFlow backend.


In [0]:
def data_summary( X_train , Y_train , X_test  , Y_test ):
  print("the shape of X_train: ",X_train.shape)
  print("the shape of Y_train: ",Y_train.shape)
  print("the shape of X_test: ",X_test.shape)
  print("the shape of Y_test: ",Y_test.shape)
  return 

In [5]:
data_summary(
    X_train,
    Y_train,
    X_test,
    Y_test
)

the shape of X_train:  (60000, 28, 28)
the shape of Y_train:  (60000,)
the shape of X_test:  (10000, 28, 28)
the shape of Y_test:  (10000,)


In [6]:
# change the shape of X_train,X_test
X_train = X_train.reshape(X_train.shape[0],784)
X_test  = X_test.reshape(X_test.shape[0],784)
data_summary(
    X_train,
    Y_train,
    X_test,
    Y_test
)


the shape of X_train:  (60000, 784)
the shape of Y_train:  (60000,)
the shape of X_test:  (10000, 784)
the shape of Y_test:  (10000,)


In [8]:
# feature scaling
sc = StandardScaler()
X_train  = sc.fit_transform(X_train)
X_test   = sc.transform(X_test)
np.mean(X_train)

4.6908810924808484e-17

In [0]:
# build model using grid search .. 
import time
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
start_time = time.time()
parameters = {'C':[0.1,1,10],'kernel':['rbf'],'gamma':[1,0.1,0.01],'max_iter':[1,10,100]}
# C=  Penalty parameter C of the error term.
# kernel = 'rbf
# gamma = Kernel coefficient for ‘rbf’
# max_iter = Hard limit on iterations within solver, or -1 for no limit.
grid_search_model = GridSearchCV( SVC() , param_grid = parameters , scoring = 'accuracy' )
grid_search_model.fit(X_train,Y_train)
end_time = time.time()

print("total time taken by grid search  to get best hyperparametr ",end_time-start_time)
# total time taken by grid search  to get best hyperparametr  4917.004335165024

In [11]:
# best parameter after tuning

print("best parameter after tuning ",grid_search_model.best_params_)

# best estimator after tuning
print("best estimator after tuning ",grid_search_model.best_estimator_)

best parameter after tuning  {'C': 1, 'gamma': 0.01, 'kernel': 'rbf', 'max_iter': 100}
best estimator after tuning  SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=100, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [13]:

# make prediction from test data
Y_pred = grid_search_model.predict(X_test)
# accuarcy report

from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
# classification report
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print( accuracy_score(Y_test,Y_pred) )


              precision    recall  f1-score   support

           0       0.87      0.99      0.93       980
           1       0.98      0.99      0.99      1135
           2       0.78      0.95      0.86      1032
           3       0.86      0.82      0.84      1010
           4       0.82      0.95      0.88       982
           5       0.80      0.92      0.85       892
           6       0.99      0.78      0.87       958
           7       0.86      0.88      0.87      1028
           8       0.94      0.76      0.84       974
           9       0.97      0.71      0.82      1009

    accuracy                           0.88     10000
   macro avg       0.89      0.88      0.87     10000
weighted avg       0.89      0.88      0.88     10000

[[ 970    0    4    2    0    3    1    0    0    0]
 [   0 1129    3    2    0    0    0    0    1    0]
 [  18    1  985    7    3    0    0   12    6    0]
 [   4    1   71  826    1   74    0   11   22    0]
 [   4    2   23    0  930   